services:
  postgres:
    image: postgres:16
    container_name: agrotrack_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agrotrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: agrotrack_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agrotrack.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
